### ISSUE TITLE
Fix errors after `bash start.sh 1` or tell us not to worry

### ISSUE THREAD

**Issue by elimisteve** [NickDaly/FreedomBuddy#9]
$ bash start.sh 1

```
ERROR:root:'hosting'
Traceback (most recent call last):
  File "/home/steve/Dropbox/programming/code/FreedomBuddy/src/santiago.py", line 278, in load_data
    data = self.shelf[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'hosting'
ERROR:root:'consuming'
Traceback (most recent call last):
  File "/home/steve/Dropbox/programming/code/FreedomBuddy/src/santiago.py", line 278, in load_data
    data = self.shelf[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'consuming'
Santiago: start
```

I can still navigate to <https://127.0.0.1:8081/freedombuddy/>, so I don't know if I should be worried about these errors. Should I be?

**Comment by NickDaly** [comment]
Fixed in commit e5ead24b, and previously (partially) fixed by commit 9a080b8a.

Now, just run:

$ ./start.sh

And it'll do the right thing by setting up default services if none are configured.
